version: "3.3"
services:
  my-app:
    image: cosmtrek/air
    # working_dir value has to be the same of mapped volume
    working_dir: /project
    ports:
      - 8000:8000
    volumes:
      - ./:/project/ 
    container_name: my-app